name: flysen_frontend_mobile
description: A template Flutter Project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  change_case: ^2.1.0
  collection: ^1.19.1
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_screenutil: ^5.9.3
  formz: ^0.8.0
  get_it: ^8.0.3
  go_router: ^17.0.0
  google_fonts: ^6.2.1
  injectable: ^2.5.0
  intl: ">=0.20.2 <0.21.0"
  json_annotation: ^4.9.0
  meta: ^1.16.0
  rxdart: ^0.28.0
  shared_preferences: ^2.3.4
  uuid: ^4.5.1
  smooth_page_indicator: ^1.2.0+1
  stroke_text: ^0.0.2
  flutter_dash: ^1.0.0
  image_picker: ^1.1.2
  http: ^1.4.0
  lottie: ^3.3.1
  jumping_dot: ^0.0.7
  chat_bubbles: ^1.6.0
  flutter_animate: ^4.5.2
  firebase_messaging: ^16.0.3
  firebase_core: ^4.2.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  mocktail: ^1.0.4
  json_serializable: ^6.8.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/google_fonts/
    - assets/icons/
    - assets/images/
    - assets/images/Square/
